# version: 2.1

# executors:
#   docker-executor:
#     docker:
#       - image: docker:20.10.7

# jobs:
#   build_and_push:
#     executor: docker-executor
#     steps:
#       # Set up Docker environment for building images
#       - setup_remote_docker:
#           version: 20.10.7

#       # Check out the code from the repository
#       - checkout

#       # Build the Docker image
#       - run:
#           name: Build Docker image
#           #command: docker build -t mgallai/vision_ai:${CIRCLE_SHA1} .
#           command: docker build -t $DOCKER_USER/vision_ai:${CIRCLE_SHA1} .


#       # Log in to Docker Hub using credentials stored in CircleCI environment variables
#       - run:
#           name: Log in to Docker Hub
#           command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

#       # Push Docker image
#       - run:
#           name: Push Docker image
#           command: docker push $DOCKER_USER/vision_ai:${CIRCLE_SHA1}

# workflows:
#   version: 2
#   build_and_push:
#     jobs:
#       - build_and_push:
#           filters:
#             branches:
#               only:
#                 - main


version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.10
    environment:
      DISPLAY: :99

  docker-executor:
    docker:
      - image: docker:20.10.7

jobs:

  build-and-test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y xvfb libxi-dev libxtst-dev xdotool
            sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest-qt
            pip install pytest pytest-qt PyQt5
            pip install pytest pytest-xvfb pyautogui
      - run:
          name: Setup PYTHONPATH
          command: |
            export PYTHONPATH="$PYTHONPATH:/home/circleci/project"
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            xvfb-run -a pytest tests/test_AI_NumberOfOutputs.py -v
            xvfb-run -a pytest tests/test_AI_PredictedCity.py -v
            xvfb-run -a pytest tests/test_AI_Preprocessing.py -v
            xvfb-run -a pytest tests/test_ButtonPanel.py -v
            xvfb-run -a pytest tests/test_IconsExist.py -v
            xvfb-run -a pytest tests/test_InformationDialog.py -v
            xvfb-run -a pytest tests/test_ModelExist.py -v
            xvfb-run -a pytest tests/test_SelectMethod.py -v
            xvfb-run -a pytest tests/test_sort_button.py -v
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  build-and-push:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - attach_workspace:
          at: .
      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_USER/vision_ai:${CIRCLE_SHA1} .
      - run:
          name: Log in to Docker Hub
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Push Docker image
          command: docker push $DOCKER_USER/vision_ai:${CIRCLE_SHA1}

workflows:
  version: 2
  build-test-and-push:
    jobs:
      - build-and-test
      - build-and-push:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main
